package com.iplanalyser;

public enum FieldsToSort {
    BY_AVERAGE,
    BY_STRIKERATE,
    BY_4s_AND_6s,
    BY_STRIKERATE_WITHMOST_4sAND6s,
    BY_AVERAGE_WITH_STRIKE_RATE,
    BY_AVERAGE_WITH_MOST_RUNS,
    BY_TOP_BOWLING_AVERAGES,
    BY_TOP_BOWLING_STRIKING_RATES,
    BY_TOP_BOWLING_ECONOMY_RATES;
}
